# Generated by Django 5.1.4 on 2024-12-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО автора')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('country', models.CharField(max_length=50, verbose_name='Страна проживания')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр книги')),
                ('year', models.IntegerField(verbose_name='Год написания')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebBook.authors', verbose_name='Автор книги')),
            ],
        ),
    ]
